"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import NavRes from "@/components/responsiveNav/NavRes";
import { useState } from "react";
import { AuthProvider } from "@/context/authContext";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Skilloop",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [navOpen, setNavOpen] = useState(false); // ← lifted state

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* Pass the state and setter to NavRes */}
          <NavRes isOpen={navOpen} setIsOpened={setNavOpen} />
          <NavBar isOpen={navOpen} setIsOpened={setNavOpen} />

          <Toaster position="top-center" />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
